### ISSUE TITLE
missing timeout cmd silently ignored on MacOS

### ISSUE THREAD

**Issue by mayurnaik** [aspire-project/chisel#1]
Running Chisel on MacOS silently fails to reduce the input program due to missing timeout command.  Possible fixes (or some combination of these):

- Emit an error when this command is not found on a system
- Update the installation instructions to mandatorily include timeout utility
- Ignore with warning the "timeout 0.1" line in test script whenever timeout command is not found on a system

Output of current run:

```
/Users/naik/projects/chisel/test/toy1$ ./run.sh 
Oracle: ./test1.sh
Input: toy1.c
local dd phase...
reducing block (size:1)
reducing block (size:1)
reducing block (size:1)
reducing block (size:6)
wc = 71
global dd phase...
========================================
                 Report                 
========================================
Global Success Ratio: 0/2
Local Success Ratio: 0/9
Learning time: 0 s
Oracle time: 0.946 s
Total time: 0.999
```

**Comment by KihongHeo** [comment]
In the new version, we do not use ```timeout``` in the test cases. And report errors if a given oracle test script does not run successfully, before running Chisel. So, Chisel runs well with all the test cases on MacOS.
