### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by Amocy-Wang** [aspire-project/chisel#3]
I chose to build chisel via docker file. However, it failed and the message is as follows: 
/chisel/src/core/Reformat.cpp:14:28: error: no member named 'vfs' in namespace 'llvm'; did you mean 'clang::vfs'?
  llvm::IntrusiveRefCntPtr<llvm::vfs::InMemoryFileSystem> InMemoryFileSystem(
                           ^~~~~~~~~
                           clang::vfs
/usr/lib/llvm-7/include/clang/Format/Format.h:31:11: note: 'clang::vfs' declared here
namespace vfs {
          ^
/chisel/src/core/Reformat.cpp:15:11: error: no member named 'vfs' in namespace 'llvm'; did you mean 'clang::vfs'?
      new llvm::vfs::InMemoryFileSystem);
          ^~~~~~~~~
          clang::vfs
/usr/lib/llvm-7/include/clang/Format/Format.h:31:11: note: 'clang::vfs' declared here
namespace vfs {
          ^
2 errors generated.
make[2]: *** [CMakeFiles/chisel.dir/build.make:167: CMakeFiles/chisel.dir/src/core/Reformat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/chisel.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by KihongHeo** [comment]
Hi,
I fixed this issue and pushed new commits. Can you try again with the latest version of Chisel?

**Comment by Amocy-Wang** [comment]
Chisel can be built successfully for me now. Thanks!
